#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/ettore/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# Set wallpaper.
fbsetbg ~/Pictures/wallpaper/saturn.jpg

# Dropbox.
dropbox start &

# Embedded terminal.
urxvt -name surxvt \
      -fn xft:"Nimbus Mono L" \
      +sb \
      -geometry 80x36+10+60 &

# Conky needs to wait some time before start ...
sleep 1 && conky &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/ettore/.fluxbox/log"
